#!/usr/bin/env bash

set -e

# Read the port from sketch.yaml
PORT=$(grep 'default_port:' sketch.yaml | awk '{print $2}')
if [ -z "$PORT" ]; then
  echo "Error: 'default_port' not found in sketch.yaml."
  exit 1
fi

# Read the FQBN from sketch.yaml
FQBN=$(grep 'fqbn:' sketch.yaml | awk '{print $2}')
if [ -z "$FQBN" ]; then
  echo "Error: 'fqbn' not found in sketch.yaml."
  exit 1
fi

echo "Using board FQBN: $FQBN"

# --- Build, Upload, and Monitor ---
BUILD_PATH="./build"

echo "Compiling sketch to '$BUILD_PATH'..."
# The compilation database is generated by default in the build path.
# The --only-compilation-database flag is not used as it prevents creating the binary required for uploading.
arduino-cli compile --fqbn "$FQBN" --build-path "$BUILD_PATH" .

echo "Uploading sketch from '$BUILD_PATH'..."
arduino-cli upload -p "$PORT" --fqbn "$FQBN" --input-dir "$BUILD_PATH" .

echo "Starting serial monitor... (Press Ctrl+C to exit)"
arduino-cli monitor -p "$PORT" --config baudrate=115200
